#####evaluar si administrador existe
POST http://localhost:1234/administradores
Content-Type: application/json

{
    "email": "fernandoguerrero@outlook.com",
    "password": "Df45?*ad-_-"
}

#####actualizar datos de un administrador
PATCH http://localhost:1234/administradores/1
Content-Type: application/json

{
    "email": "fernandoguerrero@outlook.com"
}