###PROBANDO CRUD EMPLEADOS
###recuperar todos los empleados
GET http://localhost:1234/empleados
###recuperar buscando por el nombre
GET http://localhost:1234/empleados?nombre=Jason%20Vásquez
###recuperar empleado por Id
GET http://localhost:1234/empleados/0f47612f-12da-11ef-86e4-0a0027000009
###insertar datos
POST http://localhost:1234/Empleados
Content-Type: application/json

{
    "nombre": "Olísteres Terán", 
    "fecha_ingreso": "2021-02-02", 
    "dni": "34567815",
    "telefono": "980345123", 
    "salario": 334.34, 
    "fecha_pago" : "2024-04-21",
    "tipo_empleado" : "trabajador a destajo"
}
###eliminar datos
DELETE http://localhost:1234/Empleados/90a8bcb0-ed28-4906-90ce-756a7d688e0b
###PROBAR ACTUALIZACIÓN DE DATOS
PATCH http://localhost:1234/Empleados/0f47612f-12da-11ef-86e4-0a0027000009
Content-Type: application/json

{
    "id": "0f47612f-12da-11ef-86e4-0a0027000009",
    "nombre": "Fernando Guerrero",
    "fecha_ingreso": "2022-06-11",
    "dni": "98451266",
    "telefono": "950209437",
    "salario": 1556.6,
    "fecha_pago": "2024-06-16",
    "tipo_empleado": "trabajador a destajo"
}