###PROBANDO CRUD EMPLEADOS
###recuperar datos
GET http://localhost:1234/empleados
###recuperar un empleado
GET http://localhost:1234/empleados/5
###insertar datos
POST http://localhost:1234/Empleados
Content-Type: application/json

{
    "nombre": "Yerson Guevara", 
    "fecha_ingreso": "2022-04-11", 
    "dni": "34567812",
    "telefono": "987564345", 
    "salario": 3200.34, 
    "fecha_pago" : "2024-04-15",
    "tipo_empleado" : "trabajador a destajo"
}
###eliminar datos
DELETE http://localhost:1234/Empleados/5
###PROBAR ACTUALIZACIÓN DE DATOS
PATCH http://localhost:1234/Empleados/5
Content-Type: application/json

{
    "nombre": "Yerson Guevara", 
    "fecha_ingreso": "2022-04-11", 
    "dni": "65789543",
    "telefono": "987564345", 
    "salario": 3200.34, 
    "fecha_pago" : "2024-04-16",
    "tipo_empleado" : "trabajador a destajo"
}