#####RECUPERAR TODOS LOS PEDIDOS
GET http://localhost:1234/pedidos
#####PROBAR RECUPERAR LOS PEDIDOS DE LA APLICACIÓN
GET http://localhost:1234/pedidos?polleria_id=4
#####DELETE BY ID
DELETE http://localhost:1234/pedidos/1
#####ACTUALIZAR PEDIDO
PATCH http://localhost:1234/pedidos/2
Content-Type: application/json

{
    "id_administrador": 1,
    "id_polleria": 1,
    "cantidad_kg": 30,
    "fecha": "2024-04-05",
    "tipo_papa": "Huamantanga"
}
####CREAR PEDIDO
POST http://localhost:1234/pedidos
Content-Type: application/json

{
    "id_administrador": 1,
    "id_polleria": 4,
    "cantidad_kg": 50,
    "fecha": "2024-02-11",
    "tipo_papa": "Huamantanga"
}