####Recuperar todas las ventas
GET http://localhost:1234/ventas
###Recuperar ventas de una polleria específica
GET http://localhost:1234/ventas?polleria_nombre=Súper%20Chicken
####eliminar venta por id
DELETE http://localhost:1234/ventas/70abb781-e590-4eb6-991d-e6535149d29a
####crear venta
POST http://localhost:1234/ventas/
Content-Type: application/json

{
    "id": "70abb781-e590-4eb6-991d-e6535149d29a",
    "fecha_transaccion": "2024-03-14",
    "metodo_pago": "BCP"
}